### PR TITLE
Email Integration (Backend and Frontend)

### PR DESCRIPTION
**Pull request by Aaron09**
modified app.py to integrate email sending, modified cases.html to allow for frontend input of user's email address

### CODE REVIEW

**Comment by warut-vijit** [comment]
This commit looks good. Thank you for fixing some other errors throughout the project as well. Could you please update Requirements.txt (use pipreqs) to incorporate your imports as well?

**Comment by warut-vijit** [comment]
Actually I'll do the requirements.txt myself

**Comment by cabosanlucas** [comment]
Looks good to merge, going ahead with that.

**Comment by cabosanlucas** [comment]
Merging

**Pull request merged**
